project:
  type: website
  output-dir: docs
execute:
  freeze: auto
render:
  - "!./www/*"

website:
  title: "CRNL"
  navbar:
    background: dark
    left:
      - text: "Connecting"
        menu:
        - text: "VPN"
          file: help_VPN.qmd
        - text: "Github"
          file: help_github.qmd 
      - text: "Submitting"
        menu:
        - text: "Part 1"
          file: Tutorial_Cluster_Part1.qmd
        - text: "Part 2"
          file: Tutorial_Cluster_Part2.qmd
      - text: "More"
        menu:
        - text: "VScode on the cluster"
          file: help_VScode.qmd
        

  
    right:
      - text: "About"
        file: about.qmd

format:
  html:
    theme: 
      - cerulean
      - custom.scss
    toc: true
    code-fold: true
    code-tools: true
    code-block-bg: true
    code-block-border-left: true